apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-enabled-plugins
  namespace: orion-live
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: development-infrastructure
data:
  enabled_plugins: |-
    [rabbitmq_management,rabbitmq_prometheus].
