apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orion-api
  namespace: orion-live
  labels:
    app.kubernetes.io/name: orion-live
    app.kubernetes.io/component: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-live
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orion-rabbitmq
  namespace: orion-live
  labels:
    app.kubernetes.io/name: orion-live
    app.kubernetes.io/component: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
    - port: prometheus
      path: /metrics/detailed
      params:
        family:
          - queue_coarse_metrics
        vhost:
          - /
        queue:
          - ^orion\.
      interval: 15s
      scrapeTimeout: 5s
